// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QtechOJT_Net9.Database;

#nullable disable

namespace QtechOJT_Net9.Migrations
{
    [DbContext(typeof(KanbanDbContext))]
    [Migration("20260516015033_Added_StartDate")]
    partial class Added_StartDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QtechOJT_Net9.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionDone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Main_TaskId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Main_TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("Activity_Log");
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.Assessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("Assessments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Existing",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Label = "Development / Customization",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Label = "Enhancement",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Label = "Not Applicable",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Label = "Out of Scope",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Label = "Defect",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.Holiday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Holidays");
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.Main_Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssigneeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Mandays")
                        .HasColumnType("int");

                    b.Property<int>("PhaseId")
                        .HasColumnType("int");

                    b.Property<int>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("QaAssigneeId")
                        .HasColumnType("int");

                    b.Property<int?>("SeverityId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("TargetDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Variance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("PhaseId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("QaAssigneeId");

                    b.HasIndex("SeverityId");

                    b.HasIndex("StatusId");

                    b.ToTable("Main_Tasks");
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Grouping")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("1");

                    b.Property<int>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("IsFinal")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("Phases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Grouping = "dev",
                            IsDefault = 1,
                            IsFinal = 0,
                            Label = "Backlog (Requirements)",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Grouping = "dev",
                            IsDefault = 0,
                            IsFinal = 0,
                            Label = "To Do (Ready for Dev)",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Grouping = "dev",
                            IsDefault = 0,
                            IsFinal = 0,
                            Label = "In Progress",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Grouping = "dev",
                            IsDefault = 0,
                            IsFinal = 0,
                            Label = "For Review (Dev Done)",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Grouping = "qa",
                            IsDefault = 0,
                            IsFinal = 0,
                            Label = "Client Review - UAT",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Grouping = "qa",
                            IsDefault = 0,
                            IsFinal = 0,
                            Label = "QA Execution",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Grouping = "qa",
                            IsDefault = 0,
                            IsFinal = 0,
                            Label = "Deployed (Go-Live)",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            Grouping = "qa",
                            IsDefault = 0,
                            IsFinal = 1,
                            Label = "Completed",
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PmId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TargetEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("PmId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.ProjectUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("Project_Users");
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.Severity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("Severities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "1 - Critical / Showstopper",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Label = "2 - High",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Label = "3 - Medium",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Label = "4 - Low",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Label = "5 - Cosmetic Fix",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Label = "Nice to Have",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("IsFinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("Label")
                        .IsUnique();

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#94a3b8",
                            IsDefault = 1,
                            IsFinal = 0,
                            Label = "Not Started",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Color = "#3b82f6",
                            IsDefault = 0,
                            IsFinal = 0,
                            Label = "Active",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Color = "#ef4444",
                            IsDefault = 0,
                            IsFinal = 0,
                            Label = "Blocked",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Color = "#f97316",
                            IsDefault = 0,
                            IsFinal = 0,
                            Label = "Bug Fixing",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Color = "#f59e0b",
                            IsDefault = 0,
                            IsFinal = 0,
                            Label = "Clarification Needed",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Color = "#8b5cf6",
                            IsDefault = 0,
                            IsFinal = 0,
                            Label = "For Verification",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Color = "#dc2626",
                            IsDefault = 0,
                            IsFinal = 0,
                            Label = "Failed",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            Color = "#22c55e",
                            IsDefault = 0,
                            IsFinal = 1,
                            Label = "Passed",
                            SortOrder = 8
                        });
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.Sub_Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IsDone")
                        .HasColumnType("int");

                    b.Property<int>("Main_TaskId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Main_TaskId");

                    b.ToTable("Sub_Tasks");
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.Sub_Task_Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CommentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Sub_TaskId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Sub_TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("Sub_Task_Comments");
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.Task_Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Main_TaskId")
                        .HasColumnType("int");

                    b.Property<string>("Mimetype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Main_TaskId");

                    b.ToTable("Task_Attachments");
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IsActive")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = 1,
                            Name = "Admin User",
                            Password = "AQAAAAIAAYagAAAAEI88UJCZYAeB6zVYAb3w/j29tn4IEBWuoYQGSF2K6AzHYttOvYDsl+fc31yGv7B4tQ==",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.Activity", b =>
                {
                    b.HasOne("QtechOJT_Net9.Models.Main_Task", "Main_Task")
                        .WithMany("Activity_Log")
                        .HasForeignKey("Main_TaskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QtechOJT_Net9.Models.User", "User")
                        .WithMany("Activity")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Main_Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.Main_Task", b =>
                {
                    b.HasOne("QtechOJT_Net9.Models.User", "Assignee")
                        .WithMany("DevTasks")
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QtechOJT_Net9.Models.Phase", "Phase")
                        .WithMany("Main_Tasks")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QtechOJT_Net9.Models.Project", "Project")
                        .WithMany("Main_Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QtechOJT_Net9.Models.User", "QaAssignee")
                        .WithMany("QATasks")
                        .HasForeignKey("QaAssigneeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QtechOJT_Net9.Models.Severity", "Severity")
                        .WithMany("Main_Tasks")
                        .HasForeignKey("SeverityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QtechOJT_Net9.Models.Status", "Status")
                        .WithMany("Main_Tasks")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignee");

                    b.Navigation("Phase");

                    b.Navigation("Project");

                    b.Navigation("QaAssignee");

                    b.Navigation("Severity");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.Project", b =>
                {
                    b.HasOne("QtechOJT_Net9.Models.User", "PM")
                        .WithMany("Project")
                        .HasForeignKey("PmId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PM");
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.ProjectUser", b =>
                {
                    b.HasOne("QtechOJT_Net9.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QtechOJT_Net9.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.Sub_Task", b =>
                {
                    b.HasOne("QtechOJT_Net9.Models.Main_Task", "Main_Task")
                        .WithMany("Subtasks")
                        .HasForeignKey("Main_TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Main_Task");
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.Sub_Task_Comment", b =>
                {
                    b.HasOne("QtechOJT_Net9.Models.Sub_Task", "Sub_Task")
                        .WithMany("Sub_Task_Comments")
                        .HasForeignKey("Sub_TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QtechOJT_Net9.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sub_Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.Task_Attachment", b =>
                {
                    b.HasOne("QtechOJT_Net9.Models.Main_Task", "Main_Task")
                        .WithMany()
                        .HasForeignKey("Main_TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Main_Task");
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.Main_Task", b =>
                {
                    b.Navigation("Activity_Log");

                    b.Navigation("Subtasks");
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.Phase", b =>
                {
                    b.Navigation("Main_Tasks");
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.Project", b =>
                {
                    b.Navigation("Main_Tasks");
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.Severity", b =>
                {
                    b.Navigation("Main_Tasks");
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.Status", b =>
                {
                    b.Navigation("Main_Tasks");
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.Sub_Task", b =>
                {
                    b.Navigation("Sub_Task_Comments");
                });

            modelBuilder.Entity("QtechOJT_Net9.Models.User", b =>
                {
                    b.Navigation("Activity");

                    b.Navigation("DevTasks");

                    b.Navigation("Project");

                    b.Navigation("QATasks");
                });
#pragma warning restore 612, 618
        }
    }
}
